# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://trantuanminh.com/
title: Tran Tuan Minh
email: trantminh1754@protonmail.com
author: Minh Tran
description: > # "Write an awesome description for your new site here. 
  Just another privacy blog.
copyright: 'Copyright &copy; Minh Tran. All Rights Reserved.'
credits: ''

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: Facebook
    url: https://www.facebook.com/trantuanminh1754
  - title: Blog
    url: /blog
  - title: Instagram 
    url: https://instagram.com/cuham_1754
